openapi: 3.0.0
info:
  title: SpendWise API
  version: 1.0.0
  description: API documentation for SpendWise backend
servers:
  - url: http://localhost:3000
paths:
  /api/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials
  /api/auth/register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Bad request
  /api/expenses:
    get:
      summary: Get all expenses
      responses:
        '200':
          description: List of expenses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    amount:
                      type: number
                    category:
                      type: string
                    date:
                      type: string
    post:
      summary: Add a new expense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                category:
                  type: string
                date:
                  type: string
      responses:
        '201':
          description: Expense created
        '400':
          description: Bad request
