openapi: 3.0.0
info:
  title: SpendWise API
  version: 1.0.0
  description: API documentation for SpendWise backend
servers:
  - url: http://localhost:3000

paths:
  /expenses:
    get:
      summary: Get user expenses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user expenses
          content:
            application/json:
              schema:
                type: object
                properties:
                  expenses:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        amount:
                          type: number
                        category:
                          type: string
                        date:
                          type: string
                          format: date-time
        '401':
          description: Unauthorized

  auth/google:
    get:
      summary: Initiate Google OAuth authentication
      responses:
        '302':
          description: Redirect to Google OAuth
          headers:
            Location:
              description: URL to redirect the client to
              schema:
                type: string

  auth/google/callback:
    get:
      summary: Google OAuth callback, issues JWT and redirects
      responses:
        '302':
          description: Redirect to frontend with JWT token
          headers:
            Location:
              description: Redirect URL including JWT token
              schema:
                type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
